language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^10
    - php: 7.3
      env: TYPO3_VERSION=^10
    - php: 7.4
      env: TYPO3_VERSION=^10
    - php: 7.4
      env: TYPO3_VERSION=^11
    - php: 8.0
      env: TYPO3_VERSION=^11
    - php: 8.1
      env: TYPO3_VERSION=^11
    - php: 8.2
      env: TYPO3_VERSION=^11
    - php: 8.1
      env: TYPO3_VERSION=^12
    - php: 8.2
      env: TYPO3_VERSION=^12

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/minimal=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/public/

script:
  - >
    echo;
    echo "Running unit tests";
    vendor/bin/phpunit --colors -c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -type f -name \*.php ! -path "./public/*" ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null
